name: CI

on:
  push:
    branches: [develop]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 'set Node.js'
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: install dependencies
        run: npm install

      - name: run lint
        run: npm run lint

      - name: run tests
        run: npm run test
