name: npm publish

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  publish-to-npm:
    needs: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: install dependencies
        run: npm install

      - name: npm registry init
        run: |
          npm config set registry https://registry.npmjs.org/
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
          npm whoami

      - name: publish packages
        run: npm publish
