name: Publish

on:
  push:
    branches: [master]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 'set Node.js'
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: install dependencies
        run: npm install

      - name: run lint
        run: npm run lint

      - name: run tests
        run: npm run test


  version-changelog:
    needs: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: install dependencies
        run: npm install

      - name: set git config
        run: |
          git config user.name "liuxy0551"
          git config user.email "liuxy0551@qq.com"

      - name: version
        run: npx standard-version && cat package.json

      - name: git push
        run: git push --follow-tags origin master


  publish-to-npm:
    needs: version-changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: install dependencies
        run: npm install && cat package.json
        
      - name: publish packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
